### ISSUE TITLE
Templates in job definition

### ISSUE THREAD

**Issue by bersace** [novafloss/ci-formula#27]
Support :

``` yaml
my_job:
  jenkins_job.present:
    - name: my_job
    - template: jinja
    - source: salt://my_job.xml
    - defaults:
        my_param: value
```
