### ISSUE TITLE
Put node offline before highstate

### ISSUE THREAD

**Issue by bersace** [novafloss/ci-formula#55]
Very first state.

``` yaml
node_offline:
  jenkins_node.offline:
    - name: {{ node }}
    - order: 1
```
